# Generated by Django 2.1.7 on 2020-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submissions',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='submissions')),
            ],
        ),
    ]
