# Generated by Django 2.1.2 on 2020-02-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
