# Generated by Django 2.1.2 on 2020-02-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submissions_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='submites',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('issubmitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='submissions',
            old_name='id',
            new_name='key',
        ),
    ]
